version: "3.3"

services:
  # MySQL
  db:
    container_name: "db"
    build: ./docker/db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3306"
    networks:
      - fastapi-net

  # FastAPI
  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/server
    networks:
      - fastapi-net

networks:
  fastapi-net:
    driver: bridge
